In [ ]:
import numpy as np
import math as math 
import itertools

In [ ]:
def print_matrix(mat):
    for i in range(0, len(mat)):
        print("[", end = "")
        for j in range(0, len(mat[i])):
            print(mat[i][j], end = "")
            if j != len(mat[i]) - 1:
                print("\t", end = "")
        print("]\n")



In [ ]:
#NW
gap_penalty = -2
match_award = 6
mismatch_penalty = -1

seq1 = "LNSGYHFCGGSLI"
seq2 = "LSMGCGGALY"


def match_score(alpha, beta):
    if alpha == beta:
        return match_award
    elif alpha == '-' or beta == '-':
        return gap_penalty
    else:
        return mismatch_penalty

def needleman_wunsch(seq1, seq2):
    
    n = len(seq1)
    m = len(seq2)  
    
    score = np.zeros((m+1,n+1), dtype=np.int64)
    
    for i in range(0, m + 1):
        score[i][0] = gap_penalty * i
    
    for j in range(0, n + 1):
        score[0][j] = gap_penalty * j
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = score[i - 1][j - 1] + match_score(seq1[j-1], seq2[i-1])
            delete = score[i - 1][j] + gap_penalty
            insert = score[i][j - 1] + gap_penalty
            score[i][j] = max(match, delete, insert)

    return score

print_matrix(needleman_wunsch(seq1, seq2))

[0	-2	-4	-6	-8	-10	-12	-14	-16	-18	-20	-22	-24	-26]

[-2	6	4	2	0	-2	-4	-6	-8	-10	-12	-14	-16	-18]

[-4	4	5	10	8	6	4	2	0	-2	-4	-6	-8	-10]

[-6	2	3	8	9	7	5	3	1	-1	-3	-5	-7	-9]

[-8	0	1	6	14	12	10	8	6	7	5	3	1	-1]

[-10	-2	-1	4	12	13	11	9	14	12	10	8	6	4]

[-12	-4	-3	2	10	11	12	10	12	20	18	16	14	12]

[-14	-6	-5	0	8	9	10	11	10	18	26	24	22	20]

[-16	-8	-7	-2	6	7	8	9	10	16	24	25	23	21]

[-18	-10	-9	-4	4	5	6	7	8	14	22	23	31	29]

[-20	-12	-11	-6	2	10	8	6	6	12	20	21	29	30]



In [ ]:
#NW
def needleman_wunsch_path_finder(seq1, seq2):
    
    n = len(seq1)  
    m = len(seq2)
    
    score = np.zeros((m+1,n+1), dtype=np.int64)
   
    for i in range(0, m + 1):
        score[i][0] = gap_penalty * i
    
    for j in range(0, n + 1):
        score[0][j] = gap_penalty * j
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = score[i - 1][j - 1] + match_score(seq1[j-1], seq2[i-1])
            delete = score[i - 1][j] + gap_penalty
            insert = score[i][j - 1] + gap_penalty
            score[i][j] = max(match, delete, insert)

    align1 = ""
    align2 = ""
    path = []
    
    i = m
    j = n
    
    while i > 0 and j > 0: 
        score_current = score[i][j]
        score_diagonal = score[i-1][j-1]
        score_up = score[i][j-1]
        score_left = score[i-1][j]

        if score_current == score_diagonal + match_score(seq1[j-1], seq2[i-1]):
            align1 += seq1[j-1]
            align2 += seq2[i-1]
            i -= 1
            j -= 1
            
        elif score_current == score_up + gap_penalty:
            align1 += seq1[j-1]
            align2 += '-'
            j -= 1
        elif score_current == score_left + gap_penalty:
            align1 += '-'
            align2 += seq2[i-1]
            i -= 1
        path.append((i,j))
    while j > 0:
        align1 += seq1[j-1]
        align2 += '-'
        j -= 1
    while i > 0:
        align1 += '-'
        align2 += seq2[i-1]
        i -= 1
    
    align1 = align1[::-1]
    align2 = align2[::-1]
    
    return(align1, align2, path)

output1, output2, pathway = needleman_wunsch_path_finder(seq1, seq2)

print(output1 + "\n" + output2)
print('optimal path:' , pathway)
    
   

LNS-GYHFCGGSLI
L-SMG---CGGALY
optimal path: [(9, 12), (8, 11), (7, 10), (6, 9), (5, 8), (4, 7), (4, 6), (4, 5), (4, 4), (3, 3), (2, 3), (1, 2), (1, 1), (0, 0)]


In [ ]:
    # #compute matrix D
    # for i in range(1, n + 1):
    #     for j in range(1, m + 1):
    #       mat_d = matrix_D[i - 1][j - 1] + match_score(seq1[i-1], seq2[j-1])
    #       mat_p = matrix_P[i - 1][j - 1] 
    #       mat_q = matrix_Q[i - 1][j - 1] 
    #       matrix_D[i][j] = max(mat_d, mat_p,mat_q)

    # #compute matrix P
    # for i in range(1, n + 1):
    #   for j in range(1, m + 1):
    #     mat_d = matrix_D[i - 1][j] + open_gap_penalty
    #     mat_p = matrix_P[i - 1][j] + extend_gap_penalty
    #     mat_q = matrix_Q[i - 1][j] + open_gap_penalty
    #     matrix_P[i][j] = max(mat_d,mat_p,mat_q)

    #  #compute matrix Q
    # for i in range(1, n + 1):
    #   for j in range(1, m + 1):
    #     mat_d = matrix_D[i][j-1] + open_gap_penalty
    #     mat_p = matrix_P[i][j-1] + open_gap_penalty
    #     mat_q = matrix_Q[i][j-1] + extend_gap_penalty
    #     matrix_Q[i][j] = max(mat_d,mat_p,mat_q)

In [ ]:
#Gotoh
open_gap_penalty = -6
extend_gap_penalty = -1
match_award = 6
mismatch_penalty = -1

seq1 = "LNSGYHFCGGSLI"
seq2 = "LSMGCGGALY"


def match_score(alpha, beta):
   return match_award if alpha == beta else mismatch_penalty

def g(number):
  return open_gap_penalty + extend_gap_penalty * number


def Gotoh(seq1, seq2):
    
    n = len(seq1)
    m = len(seq2)  
    
    matrix_D = np.zeros((n+1,m+1)) #, dtype=np.int64
    matrix_P = np.zeros((n+1,m+1))
    matrix_Q = np.zeros((n+1,m+1))

    for i in range(0, n):
        matrix_D[i+1][0] = g(i+1)
        matrix_P[i][0] =  np.nan
        matrix_Q[i+1][0] = -np.inf
    
    for j in range(0, m):
        matrix_D[0][j+1] = g(j+1)
        matrix_P[0][j+1] = -np.inf
        matrix_Q[0][j] = np.nan
 

    #compute matrix P (vertical)
    for i in range(1, n + 1):
      for j in range(1, m + 1):
        mat_d = matrix_D[i - 1][j] + g(1)
        mat_p = matrix_P[i - 1][j] + extend_gap_penalty
        matrix_P[i][j] = max(mat_d,mat_p)


    #compute matrix Q (horizontal)
    for i in range(1, n + 1):
      for j in range(1, m + 1):
        mat_d = matrix_D[i][j-1] + g(1)
        mat_q = matrix_Q[i][j-1] + extend_gap_penalty
        matrix_Q[i][j] = max(mat_d,mat_q)

   #compute matrix D (diagonal)
    for i in range(1, n + 1):
        for j in range(1, m + 1):
          mat_d = matrix_D[i - 1][j - 1] + match_score(seq1[i-1], seq2[j-1])
          mat_p = matrix_P[i][j]
          mat_q = matrix_Q[i][j]
          matrix_D[i][j] = max(mat_d, mat_p,mat_q)

    return matrix_D, matrix_P, matrix_Q

In [ ]:
d,p,q = Gotoh(seq1, seq2)

print("this is the D matrix")
print_matrix(d)
print("this is the P matrix")
print_matrix(p)
print("this is the q matrix")
print_matrix(q)


this is the D matrix
[0.0	-7.0	-8.0	-9.0	-10.0	-11.0	-12.0	-13.0	-14.0	-15.0	-16.0]

[-7.0	6.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0]

[-8.0	-7.0	5.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0]

[-9.0	-7.0	-1.0	4.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0	-7.0]

[-10.0	-7.0	-7.0	-2.0	10.0	-7.0	-1.0	-1.0	-7.0	-7.0	-7.0]

[-11.0	-7.0	-7.0	-7.0	-3.0	9.0	-7.0	-2.0	-2.0	-7.0	-1.0]

[-12.0	-7.0	-7.0	-7.0	-7.0	-4.0	8.0	-7.0	-3.0	-3.0	-7.0]

[-13.0	-7.0	-7.0	-7.0	-7.0	-7.0	-5.0	7.0	-7.0	-4.0	-4.0]

[-14.0	-7.0	-7.0	-7.0	-7.0	-1.0	-7.0	-6.0	6.0	-7.0	-5.0]

[-15.0	-7.0	-7.0	-7.0	-1.0	-7.0	5.0	-1.0	-7.0	5.0	-7.0]

[-16.0	-7.0	-7.0	-7.0	-1.0	-2.0	-1.0	11.0	-2.0	-7.0	4.0]

[-17.0	-7.0	-1.0	-7.0	-7.0	-2.0	-3.0	-2.0	10.0	-3.0	-7.0]

[-18.0	-7.0	-7.0	-2.0	-7.0	-7.0	-3.0	-4.0	-3.0	16.0	-4.0]

[-19.0	-7.0	-7.0	-7.0	-3.0	-7.0	-7.0	-4.0	-5.0	-4.0	15.0]

this is the P matrix
[nan	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf	-inf]

[nan	-14.0	-15.0	-16.0	-17.0	-18.0	-19.0	-20.0	-21.0	-22.0	-23.0]

[nan	-7.0	-7.0	-

In [ ]:
#SMW
gap_penalty = -2
match_award = 6
mismatch_penalty = -1

seq1 = "LNSGYHFCGGSLI"
seq2 = "LSMGCGGALY"


def match_score(alpha, beta):
    if alpha == beta:
        return match_award
    elif alpha == '-' or beta == '-':
        return gap_penalty
    else:
        return mismatch_penalty

def smith_waterman(seq1, seq2):
    
    n = len(seq1)
    m = len(seq2)  
    
    score = np.zeros((m+1,n+1), dtype=np.int64)
    
    for i in range(0, m + 1):
        score[i][0] = 0
    
    for j in range(0, n + 1):
        score[0][j] = 0
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = score[i - 1][j - 1] + match_score(seq1[j-1], seq2[i-1])
            delete = score[i - 1][j] + gap_penalty
            insert = score[i][j - 1] + gap_penalty
            score[i][j] = max(match, delete, insert,0)

    return score

print_matrix(smith_waterman(seq1, seq2))

[0	0	0	0	0	0	0	0	0	0	0	0	0	0]

[0	6	4	2	0	0	0	0	0	0	0	0	6	4]

[0	4	5	10	8	6	4	2	0	0	0	6	4	5]

[0	2	3	8	9	7	5	3	1	0	0	4	5	3]

[0	0	1	6	14	12	10	8	6	7	6	4	3	4]

[0	0	0	4	12	13	11	9	14	12	10	8	6	4]

[0	0	0	2	10	11	12	10	12	20	18	16	14	12]

[0	0	0	0	8	9	10	11	10	18	26	24	22	20]

[0	0	0	0	6	7	8	9	10	16	24	25	23	21]

[0	6	4	2	4	5	6	7	8	14	22	23	31	29]

[0	4	5	3	2	10	8	6	6	12	20	21	29	30]



In [ ]:
#SMW
def smith_waterman_path_finder(seq1, seq2):
    
    n = len(seq1)  
    m = len(seq2)
    align1 = ""
    align2 = ""
    path = []

    score = np.zeros((m+1,n+1), dtype=np.int64)
   
    for i in range(0, m + 1):
        score[i][0] = 0
    
    for j in range(0, n + 1):
        score[0][j] = 0
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = score[i - 1][j - 1] + match_score(seq1[j-1], seq2[i-1])
            delete = score[i - 1][j] + gap_penalty
            insert = score[i][j - 1] + gap_penalty
            score[i][j] = max(match, delete, insert,0)

 

    maximum = np.unravel_index(np.argmax(score,axis=None), score.shape)
    i = maximum[0]
    j = maximum[1]
    path.append(maximum)

    while i > 0 and j > 0:
        if score[i][j] == 0:
          break;
        else:
          score_current = score[i][j]
          score_diagonal = score[i-1][j-1]
          score_up = score[i][j-1]
          score_left = score[i-1][j]

          if score_current == score_diagonal + match_score(seq1[j-1], seq2[i-1]):
              align1 += seq1[j-1]
              align2 += seq2[i-1]
              i -= 1
              j -= 1
              
          elif score_current == score_up + gap_penalty:
              align1 += seq1[j-1]
              align2 += '-'
              j -= 1
          elif score_current == score_left + gap_penalty:
              align1 += '-'
              align2 += seq2[i-1]
              i -= 1
          path.append((i,j))
    while j > 0:
        align1 += seq1[j-1]
        align2 += '-'
        j -= 1
    while i > 0:
        align1 += '-'
        align2 += seq2[i-1]
        i -= 1
    
    align1 = align1[::-1]
    align2 = align2[::-1]
    
    return(align1, align2, path)

output1, output2, pathway = smith_waterman_path_finder(seq1, seq2)

print(output1 + "\n" + output2)
print('optimal path:' , pathway)

LNS-GYHFCGGSL
L-SMG---CGGAL
optimal path: [(9, 12), (8, 11), (7, 10), (6, 9), (5, 8), (4, 7), (4, 6), (4, 5), (4, 4), (3, 3), (2, 3), (1, 2), (1, 1), (0, 0)]


In [ ]:
# def matrix(a, b):
#     match_score=6 
#     gap_cost=2
#     mismatch_score = 1
#     H = np.zeros((len(a) + 1, len(b) + 1), np.int)

#     for i, j in itertools.product(range(1, H.shape[0]), range(1, H.shape[1])):
#         match = H[i - 1, j - 1] + (match_score if a[i - 1] == b[j - 1] else - mismatch_score)
#         delete = H[i - 1, j] - gap_cost
#         insert = H[i, j - 1] - gap_cost
#         H[i, j] = max(match, delete, insert, 0)
#     return H

In [ ]:
# def traceback(H, b, b_='', old_i=0):
#     H_flip = np.flip(np.flip(H, 0), 1)
#     #print(H_flip)
#     i_, j_ = np.unravel_index(H_flip.argmax(), H_flip.shape)
#     #print(i_,j_)
#     i, j = np.subtract(H.shape, (i_ + 1, j_ + 1))
#     #print(i,j)
#     if H[i, j] == 0:
#         return b_, j
#     b_ = b[j - 1] + '-' + b_ if old_i - i > 1 else b[j - 1] + b_
#     #print(b_)
#     return traceback(H[0:i, 0:j], b, b_, i)

In [ ]:
# def smith_waterman(a, b):
#     H = matrix(a, b)
#     b_, pos = traceback(H, b)
#     return pos, pos + len(b_)

In [ ]:
# seq1 = "LNSGYHFCGGSLI"
# seq2 = "LSMGCGGALY"
# a, b = seq1,seq2
# H = matrix(a, b)
# print(H)
# print(traceback(H, b))
# local, int = traceback(H,b)

# a, b = seq1,seq2
# start, end = smith_waterman(a, b)
# #print(a)
# #print(local)
# #print(b)
# # bei max starten und so lange opt alignment bis man auf eine 0 trifft, dann ende
# # 

[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  4  2  0  0  0  0  0  6  4]
 [ 0  4  5  3  1  0  0  0  0  4  5]
 [ 0  2 10  8  6  4  2  0  0  2  3]
 [ 0  0  8  9 14 12 10  8  6  4  2]
 [ 0  0  6  7 12 13 11  9  7  5 10]
 [ 0  0  4  5 10 11 12 10  8  6  8]
 [ 0  0  2  3  8  9 10 11  9  7  6]
 [ 0  0  0  1  6 14 12 10 10  8  6]
 [ 0  0  0  0  7 12 20 18 16 14 12]
 [ 0  0  0  0  6 10 18 26 24 22 20]
 [ 0  0  6  4  4  8 16 24 25 23 21]
 [ 0  6  4  5  3  6 14 22 23 31 29]
 [ 0  4  5  3  4  4 12 20 21 29 30]]
('L-SG-CGG-L', 0)
